### PR TITLE
Add spell check workflow template

### LINKED ISSUE #9: Add template for spell-check workflow for self-service

### PR DESCRIPTION
**Pull request by per1234**
This will allow the workflow to be added to any public repository under the 107-systems organization by selecting it
from GitHub's "Actions" UI.

https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/sharing-workflows-with-your-organization#creating-a-workflow-template

Fixes https://github.com/107-systems/.github/issues/9

### CODE REVIEW

**Comment by per1234** [comment]
What I'm proposing here is a departure from the approach previously used. In the recent codespell 2.0.0 release, support was added for a configuration file. So, rather than defining the codespell configuration in the workflow, we now have the option of defining it in a standardized configuration file. The advantage of this approach is it allows the same configuration to be used when running codespell locally as when run by the CI workflow.

This configuration file should be in the root of the repository:
https://github.com/codespell-project/codespell#using-a-config-file
>When running codespell, it will check in the current directory for a file named `setup.cfg` or `.codespellrc` (or a file specified via `--config`), containing an entry named `[codespell]`.

The `--config` option has not yet been added to the `codespell-project/actions-codespell` action (though it is soon to come). So I don't know how you feel about adding a file to the root of the repositories. The ignore words list can be defined in this configuration file, so it replaces the current `etc/codespell-ignore-words-list.txt`.

Example:
```
[codespell]
# In the event of a false positive, add the problematic word, in all lowercase, here:
ignore-words-list = wan
check-filenames =
check-hidden =
skip = ./.git
```

**Comment by aentinger** [comment]
After giving the subject a bit of thought I've decided that I would be okay with a file in the root of the repository if the Arduino IDE will not pick it up. From all the available options I think I like `.codespellrc` best, it reminds me of `travis.yml` and similar styled files where you just know what they do when you see those files.

If I understand you correctly we would have to mitigate the existing ignore words into that config file once the action is updated?

**Comment by per1234** [comment]
>we would have to mitigate the existing ignore words into that config file once the action is updated?

No, the `codespell-project/actions-codespell` action will continue to support specifying the path to the ignore words list via the `ignore_words_file` input just as always. The configuration file feature added in codespell 2.0.0 is only an additional method for configuring codespell and the action. I'm not sure what was the cause of the major version bump of codespell and I don't see any documentation that would make it easy to find out.

But if we switch the existing workflows ([example](https://github.com/107-systems/107-Arduino-UAVCAN/blob/master/.github/workflows/spell-check.yml)) to match this one, then the ignore words list will need to be moved from `./etc/codespell-ignore-words-list.txt` to `./.codespellrc`, not because of anything to do with codespell or the codespell action, but simply because the workflow isn't configured to read the ignore words list from that file.

**Comment by aentinger** [comment]
I see. Moving the ignore words list is all right with me. Can you please open the required PRs, once this change comes into effect?

**Comment by per1234** [comment]
OK, will do.

**Review by aentinger — APPROVED** [review]

**Pull request merged**
